region: us-east-1

artifactPath: target/user-search-etl-1.0-SNAPSHOT.jar

memorySize: 512

timeout: 180

deploymentBucketName: ntwhitfi-serverless-deployment-bucket

lambdaRole: arn:aws:iam::380986832728:role/UserETLRole-dev

roleToDepartmentMap: '{
  "Developer": "IT",
  "HR Manager": "HR",
  "Facility manager": "Facilities"
}'

userETLStartCommand: start

sns:
  endpoint: nate63x2@gmail.com
  protocol: email

tags:
  - Key: app
    Value: UserSearch
  - Key: gitRepo
    Value: user-search