version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless
      - npm install -g @vue/cli

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying CloudFormation stacks
      - cd aws_infrastructure
      # Deploy the IAM roles
      - aws cloudformation update-stack --template-body file://UserAuthIamRole.yml --stack-name UserAuthIAMRole-${ENVIRONMENT} --parameters ParameterKey=Environment,ParameterValue=${ENVIRONMENT},ParameterKey=UserPoolId,ParameterValue=${USER_POOL_ID} --capabilities CAPABILITY_NAMED_IAM
      - aws cloudformation update-stack --template-body file://UserETLIAM.yml --stack-name UserSearchETLIAMRole-${ENVIRONMENT} --parameters ParameterKey=UserSearchDynamoDBTableName,ParameterValue=UserSearchTable-${ENVIRONMENT},ParameterKey=Environment,ParameterValue=${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM
      - aws cloudformation update-stack --template-body file://UserRequestAuthorizerIamRole.yml --stack-name UserRequestAuthIAMRole-${ENVIRONMENT} --parameters ParameterKey=UserPoolId,ParameterValue=${USER_POOL_ID},ParameterKey=Environment,ParameterValue=${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM
      - aws cloudformation update-stack --template-body file://UserSearchIAM.yml --stack-name UserSearchRole-${ENVIRONMENT} --parameters ParameterKey=DynamoDBTableName,ParameterValue=UserSearchTable-${ENVIRONMENT},ParameterKey=Environment,ParameterValue=${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM
      - cd ../user-search-auth
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-etl
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-request-authorizer
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-service
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-ui
      - chmod +x deploy.sh
      - ./deploy.sh
artifacts:
  files:
    - '**/*'