version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying CloudFormation stacks
      - cd aws_infrastructure
      # deploy the IAM roles to us-east-1
      - export REGION="us-east-1"
      - aws cloudformation deploy --template-file UserAuthIamRole.yml --stack-name UserAuthIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      - aws cloudformation deploy --template-file UserETLIAM.yml --stack-name UserSearchETLIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      - aws cloudformation deploy --template-file UserRequestAuthorizerIamRole.yml --stack-name UserRequestAuthIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      - aws cloudformation deploy --template-file UserSearchIAM.yml --stack-name UserSearchRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      # Deploy to us-east-1
      - cd ../user-search-auth
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../user-search-etl
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../user-search-request-authorizer
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../quarkus-user-search-service
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../user-search-ui
      - export CLOUDFRONT_DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID_EAST}"
      - export BUCKET_NAME="${BUCKET_NAME_EAST}"
      - chmod +x deploy.sh
      - ./deploy.sh

      # deploy the IAM roles to us-west-1
      - export REGION="us-west-1"
      - cd ../aws_infrastructure
      - aws cloudformation deploy --template-file UserAuthIamRole.yml --stack-name UserAuthIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      - aws cloudformation deploy --template-file UserETLIAM.yml --stack-name UserSearchETLIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      - aws cloudformation deploy --template-file UserRequestAuthorizerIamRole.yml --stack-name UserRequestAuthIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      - aws cloudformation deploy --template-file UserSearchIAM.yml --stack-name UserSearchRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --region ${REGION}
      # Deploy to us-west-1
      - cd ../user-search-auth
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../user-search-etl
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../user-search-request-authorizer
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../quarkus-user-search-service
      - serverless -v --stage $ENVIRONMENT deploy --region ${REGION}
      - cd ../user-search-ui
      - export CLOUDFRONT_DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID_WEST}"
      - export BUCKET_NAME="${BUCKET_NAME_WEST}"
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - '**/*'