version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Requires corretto when using the AMZN linux 2 docker image
      nodejs: 12
    commands:
      - npm install -g serverless
      - npm install -g @vue/cli
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying CloudFormation stacks
      - cd aws_infrastructure
      # deploy the IAM roles
      - aws cloudformation update-stack --template-body file://UserAuthIamRole.yml --stack-name UserAuthIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM
      - aws cloudformation update-stack --template-body file://UserETLIAM.yml --stack-name UserSearchETLIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM
      - aws cloudformation update-stack --template-body file://UserRequestAuthorizerIamRole.yml --stack-name UserRequestAuthIAMRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM
      - aws cloudformation update-stack --template-body file://UserSearchIAM.yml --stack-name UserSearchRole-${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM
      - cd ../user-search-auth
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-etl
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-request-authorizer
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-service
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-ui
      - chmod +x deploy.sh
      - ./deploy.sh
artifacts:
  files:
    - '**/*'