version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g serverless

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying CloudFormation stacks
      - cd aws_infrastructure
      # Deploy the IAM roles
      - aws cloudformation deploy --template-file UserAuthIamRole.yml --stack-name UserAuthIAMRole-${ENVIRONMENT} --parameter-overrides Environment=${ENVIRONMENT} UserPoolId=${USER_POOL_ID} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file UserETLIAM.yml --stack-name UserSearchETLIAMRole-${ENVIRONMENT} --parameter-overrides UserSearchDynamoDBTableName=UserSearchTable-${ENVIRONMENT} Environment=${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file UserRequestAuthorizerIamRole.yml --stack-name UserRequestAuthIAMRole-${ENVIRONMENT} --parameter-overrides UserPoolId=${USER_POOL_ID} Environment=${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - aws cloudformation deploy --template-file UserSearchIAM.yml --stack-name UserSearchRole-${ENVIRONMENT} --parameter-overrides DynamoDBTableName=UserSearchTable-${ENVIRONMENT} Environment=${ENVIRONMENT} --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
      - cd ../user-search-auth
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-etl
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-request-authorizer
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-service
      - serverless -v --stage $ENVIRONMENT deploy
      - cd ../user-search-ui
      - chmod +x deploy.sh
      - ./deploy.sh
artifacts:
  files:
    - '**/*'