AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  UserSearchServiceStackeryDev:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: '3.0'
        info:
          title: !Sub ${AWS::StackName}-HttpApi
          version: '1.0'
        paths:
          /user/search:
            get:
              responses: {}
      FailOnWarnings: true
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
          - X-Amz-User-Agent
          - X-Apollo-Tracing
  UserSearchHandlerStackery:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-UserSearchHandlerStacke
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: UserSearchHandlerStackery
      CodeUri: ./
      Handler: ntwhitfi.user.search.service.handler.UserSearchHandler
      Runtime: java8
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserSearchTableStackery
      Events:
        UserSearchServiceStackeryDevGETusersearch:
          Type: HttpApi
          Properties:
            Path: /user/search
            Method: GET
            ApiId: !Ref UserSearchServiceStackeryDev
            PayloadFormatVersion: '2.0'
            TimeoutInMillis: 29000
      Environment:
        Variables:
          GET_ALL_TYPE: all
          QUERY_TYPE: query
          TABLE_NAME: !Ref UserSearchTableStackery
          TABLE_ARN: !GetAtt UserSearchTableStackery.Arn
  UserSearchTableStackery:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      TableName: !Sub ${AWS::StackName}-UserSearchTableStackery
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)