AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the IAM Roles for the User Search CodePipeline and CodeBuild projects.

Parameters:
  Author:
    Description: Author's name
    Type: String
    Default: ntwhitfi
    MinLength: 3
    MaxLength: 30

Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "UserSearchCodePipelineRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: UserSearchCICDPipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codepipeline:EnableStageTransition
                  - codepipeline:DisableStageTransition
                Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:UserSearch*"
        - PolicyName: UserSearchCICDCodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codebuild:GetResourcePolicy
                  - codebuild:BatchGetBuilds
                  - codebuild:ImportSourceCredentials
                  - codebuild:InvalidateProjectCache
                  - codebuild:StartBuild
                  - codebuild:StopBuild
                Resource: !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/user-search*"
        - PolicyName: UserSearchCICDS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketPolicy
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:PutObjectVersion
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::ntwhitfi-codebuild-artifacts*"
                  - !Sub "arn:aws:s3:::ntwhitfi-codebuild-artifacts*/*"
        - PolicyName: UserSearchCICDIAMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:PassRole
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/UserSearch*"
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "UserSearchCodeBuildRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: UserSearchCICDCloudFormationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateStack
                  - cloudformation:CreateUploadBucket
                  - cloudformation:DeleteStack
                  - cloudformation:GetStackPolicy
                  - cloudformation:SetStackPolicy
                  - cloudformation:UpdateStack
                  - cloudformation:UpdateStackSet
                  - cloudformation:UpdateTerminationProtection
                Resource:
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/UserSearch*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/User-Search*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/user-search*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/UserAuth*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/User-Auth*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/user-auth*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/UserRequest*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/user-request*"
                  - !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/User-Request*"
        - PolicyName: UserSearchCodeBuildCloudFormationAllPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                  - cloudformation:TagResource
                  - cloudformation:UntagResource
                  - cloudformation:List*
                  - cloudformation:Describe*
                Resource: "*"
        - PolicyName: UserSearchCodeBuildServerlessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:PATCH
                  - apigateway:GET
                  - apigateway:POST
                  - apigateway:PUT
                  - apigateway:HEAD
                  - apigateway:OPTIONS
                  - apigateway:DELETE
                  - apigateway:UpdateRestApiPolicy
                  - lambda:AddLayerVersionPermission
                  - lambda:AddPermission
                  - lambda:CreateAlias
                  - lambda:CreateEventSourceMapping
                  - lambda:CreateFunction
                  - lambda:DeleteAlias
                  - lambda:DeleteEventSourceMapping
                  - lambda:DeleteFunction
                  - lambda:DeleteFunctionConcurrency
                  - lambda:DeleteFunctionEventInvokeConfig
                  - lambda:DeleteLayerVersion
                  - lambda:DeleteProvisionedConcurrencyConfig
                  - lambda:InvokeAsync
                  - lambda:InvokeFunction
                  - lambda:PublishLayerVersion
                  - lambda:PublishVersion
                  - lambda:PutFunctionConcurrency
                  - lambda:PutFunctionEventInvokeConfig
                  - lambda:PutProvisionedConcurrencyConfig
                  - lambda:RemoveLayerVersionPermission
                  - lambda:RemovePermission
                  - lambda:Update*
                Resource:
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UserSearchHandler-*"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UserETLHandler-*"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UserAuthHandler-*"
                  - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:RequestAuthorizerHandler-*"
                  - !Sub "arn:aws:apigateway:${AWS::Region}::/restapis*"
              - Effect: Allow
                Action:
                  - lambda:Get*
                  - lambda:List*
                Resource: "*"
        - PolicyName: UserSearchCodeBuildS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetBucketPolicy
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:PutObjectVersion
                  - s3:ListAllMyBuckets
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::ntwhitfi*"
                  - !Sub "arn:aws:s3:::ntwhitfi*/*"
        - PolicyName: UserSearchCodeBuildSSMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:DescribeParameters
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParametersByPath
                  - ssm:PutParameter
                Resource:
                  - "*"
        - PolicyName: UserSearchCICDIAMPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:ListRoles
                  - iam:PassRole
                Resource:
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/User*"
        - PolicyName: UserSearchCodeBuildCloudFrontPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                  - cloudfront:GetDistribution
                  - cloudfront:GetStreamingDistribution
                  - cloudfront:GetDistributionConfig
                  - cloudfront:GetInvalidation
                  - cloudfront:ListInvalidations
                  - cloudfront:ListStreamingDistributions
                  - cloudfront:ListDistributions
                Resource: "*"
        - PolicyName: UserSearchCodeBuildSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:CreateInvalidation
                  - sns:Get*
                  - sns:List*
                  - sns:Describe*
                  - sns:AddPermission
                  - sns:CreateTopic
                  - sns:DeleteTopic
                  - sns:GetEndpointAttributes
                  - sns:GetPlatformApplicationAttributes
                  - sns:RemovePermission
                  - sns:TagResource
                Resource: "*"
        - PolicyName: UserSearchCodeBuildCloudWatchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:List*
                  - cloudwatch:Describe*
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:DisableAlarmActions
                  - cloudwatch:EnableAlarmActions
                  - cloudwatch:PutMetricAlarm
                  - cloudwatch:TagResource
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:Describe*
                  - logs:List*
                  - logs:PutLogEvents
                  - logs:DeleteLogGroup
                  - logs:DeleteLogStream
                  - logs:DeleteMetricFilter
                  - logs:DeleteResourcePolicy
                  - logs:DeleteRetentionPolicy
                  - logs:DeleteSubscriptionFilter
                  - logs:TagLogGroup
                Resource: "*"
              - Effect: Allow
                Action:
                  - events:DeleteRule
                  - events:DescribeRule
                  - events:DisableRule
                  - events:EnableRule
                  - events:ListRules
                  - events:ListTargetsByRule
                  - events:PutPermission
                  - events:PutRule
                  - events:PutTargets
                  - events:RemovePermission
                  - events:RemoveTargets
                  - events:TagResource
                  - events:TestEventPattern
                Resource: "*"